### ISSUE TITLE
Suspended games don't survive computer going to sleep on Windows

### ISSUE THREAD

**Issue by fleetsing** [Merrit/nyrna#120]
I've been having problems using Nyrna on both my Windows 10 desktop and my GPD Win Max 2 handheld that's running Windows 11.

While Nyrna works perfectly when the devices are awake, as soon as I put either device to sleep and wake it back up the games I have suspended crash. Resource monitor responds their status as "Not Responding", but Nyrna shows them as green, and tries to suspend them again when clicked, and hangs itself if they're clicked a second time.

I've tested several games from Steam and GOG (Persona 5 Royal, The Ascent, Slay the Spire, Batman Arkham Asylum, Sunless Skies, etc. to name a few), and they all behave like this, but programs like Notebook are able to resume normally. I've tested how some of those games handle the computer sleeping when they're not suspended, and they run just fine after the machine wakes up. It seems to specifically be related to them being suspended when going to sleep/waking up.

Both of the devices use S3 sleep state, and are running up to date versions of their OS.

Is this a known problem with Windows, or is there something I might be able to do on my end to fix it?

**Comment by Merrit** [comment]
This is essentially a known, unfixable issue.. Windows doesn't even provide an official way to interact with processes like this, and the fact that it works at all is amazing :)

Crashes and the like are thankfully not common, but also not entirely unexpected simply due to how Windows works. I don't recommend suspending the computer while processes are already suspended like this (though I definitely get why you would want to!).

Since we can't resolve this I am going to close the issue. If you feel it needs more attention, feel free to reopen it!

Thank you for the detailed bug report - much appreciated your attention and care! :blue_heart:
