### ISSUE TITLE
[BUG] Wrong language in setting menu.

### ISSUE THREAD

**Issue by n4n15** [Merrit/nyrna#181]
Hello,

There is probably a bug with the language detection.
My Windows 11 system is in French and the setting menu is in German.

Weirdly, the main menu seem to be in English. Or at least display some message box in English. I.E in screenshoots.

I have try to replicate the problem in Virtual Machine and I can do so in Windows 10 French and on Arch Linux with French.

![Capture d'écran 2023-08-16 105923](https://github.com/Merrit/nyrna/assets/996164/8089e7b4-5ff2-4a01-a91f-cb943d714333)
![Capture d'écran 2023-08-15 114724](https://github.com/Merrit/nyrna/assets/996164/6a9e0e1a-2d94-40d1-8271-cd1466e0729f)

I am on last Nyrna 2.16 from Github for both of my Windows, and I have use the last Flatpack for my Arch.

Regards.

**Comment by Merrit** [comment]
Thanks for the report, I will look into it :)

**Comment by Merrit** [comment]
Please give this beta build a try, see if it resolves the issue for you. There is no French translations yet, but it should fallback to English rather than German.

[Nyrna-Linux-Portable.tar.gz](https://github.com/Merrit/nyrna/files/12371728/Nyrna-Linux-Portable.tar.gz)
[Nyrna-Windows-Portable.zip](https://github.com/Merrit/nyrna/files/12371731/Nyrna-Windows-Portable.zip)

**Comment by Merrit** [comment]
Glad to hear it!

Merci beaucoup for your detailed and helpful bug report :grin: 💙
