### ISSUE TITLE
[BUG] Starts with white screen when added to Task Scheduler - Windows 10

### ISSUE THREAD

**Issue by ceedveed** [Merrit/nyrna#31]
**Describe the bug**
Executing shortcut runs Nyrna normally. But I need to run as administrator for my games to suspend. If I try to run the program by adding a task in Task Scheduler, Nyrna only shows a white screen within its window. I use task scheduler because I want Nyrna to run as administrator at startup.

**To Reproduce**
1. Go to task scheduler
2. Make a task to run Nyrna with highest privileges (I made one to run on log on)
3. Run task manually to test
4. White screen in Nyrna window

**Expected behavior**
I expect Nyrna to show the running programs as it is usually does when executing the shortcut from the start menu.

**Screenshots**

**Software (please complete the following information):**
 - OS: Windows 10 20H2
 - Nyrna v2.0-beta.1

**Additional context**
If I copy the Nyrna shortcut to the Startup menu, it will run at startup. But I can't run it as administrator. My games won't suspend unless Nyrna is run as administrator.

**Comment by Merrit** [comment]
This appears to be a [well-known issue](https://superuser.com/questions/929225/how-to-run-a-program-as-an-administrator-at-startup-on-windows-10) with trying to start GUI apps as admin on startup for Windows.

Do you already have other GUI apps successfully running as admin on startup?

**Comment by ceedveed** [comment]
> This appears to be a [well-known issue](https://superuser.com/questions/929225/how-to-run-a-program-as-an-administrator-at-startup-on-windows-10) with trying to start GUI apps as admin on startup for Windows.
> 
> 
> 
> Do you already have other GUI apps successfully running as admin on startup?

Yes. DS4Windows runs successfully in task scheduler as admin.  In the past I've also run Intel Extreme Running Utility as well.

**Comment by Merrit** [comment]
I can get Nyrna to run as admin on logon by fiddling with Task Scheduler settings, but the workaround basically breaks Nyrna - I presume being launched by the system this way it has no parent console attached.

I consider this a fault with Windows rather than Nyrna. As such I would consider a contribution for a work-around, otherwise I believe this is out of scope for this project.

I do feel the frustration of not getting things like this to work as one wishes though, the sort of thing that pushed me to adopt Linux full-time instead of dealing with these Windows oddities :)

**Comment by Merrit** [comment]
I took a couple more stabs at this, however Windows is quite stubborn on this matter.

Wish I could've provided a work around for you, but I can't really devote more time to this. As such I am closing as notabug, since this is really a Windows issue.

Thanks for opening the issue, and I hope having to start Nyrna manually won't be too large an annoyance :heart:

**Comment by unphased** [comment]
@Merrit would you be open to contributions augmenting the codebase with a layer of abstraction so that 

- process detection and suspension/resume do not rely on it having a window to exist (if feasible)
- this means it could then be launched by task scheduler as admin
- it could provide an API so other apps can easily incorporate its behavior

**Comment by Merrit** [comment]
@unphased that's a good idea. It would definitely be feasible to split that functionality off into a separate Dart program or shared library, which the GUI can communicate with.

The [issue](https://superuser.com/questions/929225/how-to-run-a-program-as-an-administrator-at-startup-on-windows-10) I linked previously suggests however that there is inconsistent behaviour experienced with the various workarounds discussed, so a good first step would be to verify that launching non-GUI apps as admin in this way does in fact work as desired. I am somewhat hesitant regarding the work on this given that Windows doesn't provide a native way of doing this, and even if we could get it working it could easily break with a Windows update.
