### ISSUE TITLE
Keyboard Shortcut?

### ISSUE THREAD

**Issue by BluegunnerX** [Merrit/nyrna#34]
I was told Nyrna had a keyboard shortcut for pausing the current tab, and that it was rebindable, but I do not see this in the version I downloaded. couldi t be this was an earlier function that was removed?

**Comment by Merrit** [comment]
Suspending the current, active application is available by calling the Nyrna executable with the `-t` or `--toggle` flag.

https://nyrna.merritt.codes/usage#toggle-active-window

In Linux this can be done with a custom shortcut that calls has an action like so (substitute your actual path):

> ~/Applications/Nyrna/nyrna -t

On Windows this can be done by editing the Start Menu / Desktop shortcut (or editing a copy) - and choosing a shortcut in the properties of that shortcut, as well as editing the "target" field to include the `-t` at the end.

I would like to look into making this an in-app configuration since that is much simpler and easier, but I haven't had the time to do so as yet. 😄

**Comment by andreycout** [comment]
So, I know this is closed and all, but Windows Hotkey is not actually working (or it works... sometimes?) I tried with the method suggested of setting a hotkey in a windows shortcut and adding the -t flag. Nyrna seems to open an instance when pressing the combination and closes immediately, but the foreground application isn't suspended. In some cases I did manage to get it to suspend, but pressing the hotkey again doesn't resume the process. Also tried created an AutoHotkey script to manage the hotkey but got the exact same result. It almost feels like Nyrna suspending itself and then closing itself, some kind of timing issue, I don't know.

**Comment by Merrit** [comment]
Interesting.. This was working before, and now doesn't. Wondering if a Windows update broke something..

Could you create a new issue, and include your Windows version & an application you've tried to suspend that failed? I will have to look into this some.
