### ISSUE TITLE
Linux system integration

### ISSUE THREAD

**Issue by BlueManCZ** [Merrit/nyrna#47]
I was thinking, what is the best way to install the current Nyrna to the Linux system? I mean, I know I can just take a `portable.zip` and extract it to the `/usr/share/nyrna` and then create symlinks to executables in `/usr/bin`, but what about `toggle_active_window`? Shouldn't it be at least renamed to `nyrna-toggle` or shouldn't a launch parameter like `nyrna --toggle` be considered to replace this?

**Comment by Merrit** [comment]
> what is the best way to install the current Nyrna to the Linux system?

Since it is not available from a repo but rather as a portable app, I think the presumption is that it will be placed somewhere like `$HOME/Applications/<app>`, which makes it easily accessible & simple to update (drop / extract new files ontop of old). There is also an item in Nyrna's settings to add itself to the system launcher.

> what about toggle_active_window? Shouldn't it be at least renamed to nyrna-toggle or shouldn't a launch parameter like nyrna --toggle be considered to replace this?

Not sure I understand.. `toggle_active_window` shouldn't appear in the launcher, rather it should be launched with a hotkey - so I am not sure why the name would need changing? So either having the hotkey launch the executable directly via something like `~/Applications/Nyrna/toggle_active_window`, or you could even add the Nyrna directory to path and then the hotkey could just do `toggle_active_window`. Unless I misunderstood entirely your question? 😄

**Comment by BlueManCZ** [comment]
Yes, I get it. But presumptions are sometimes bad. I for example don't like placing applications in my home folder, because you have to update it manually, often you even forget where you placed it, and so on. I like it when my package manager does all the job for me, the application is easily updatable, findable and available to all users. I'm not saying you should package it, but someone else may want to.

And in the current state, it is not very clear from the application or even the user's perspective when entering the portable archive, what the whole thing does.

--------------
When you imagine Linux user without any knowledge about the app, you can expect this thought process:

_Hmm, there are two binaries. Let's see what they can do._
```
./nyrna --help
flutter: Unknown argument: FormatException: Could not find an option named "help".
```
_alright, let's start it then. Cool, it works. What about the second one?_
```
./toggle_active_window --help
```
_Whoops, something happend. I guess it paused and minimalized my terminal._

--------------

`toggle_active_window` binary is fine. But I think it should be an inside tool for nyrna and there should be a way to invoke it with the main binary `nyrna --toggle` for example, with `nyrna --help` explaining the usage of the whole application.

**Comment by Merrit** [comment]
Yes I think I see where you are coming from. Thanks for the insight, much appreciated 😀 

> ./nyrna --help
> flutter: Unknown argument: FormatException: Could not find an option named "help".

I guess it might be nice to provide some sort of response instead of an exception, yeah.

> Whoops, something happend. I guess it paused and minimalized my terminal.

lol.. definitely not ideal (though.. perhaps somewhat expected? It did what its name implied 😄)

>  it should be an inside tool for nyrna and there should be a way to invoke it with the main binary nyrna --toggle for example

Yes, for sure I would prefer this as well. Unfortunately Flutter doesn't currently have a way to interact with the application from CLI only - any interaction launches the GUI. (Flutter's desktop support *is* still only in beta, so..)

This is why I refactored Nyrna to remove the part that toggles that active window into its own self-contained dart application that has no dependencies on the GUI. Prior to this it was doing the very ugly thing of:

- launching the GUI
- catching the flag it was passed
- suspending / resuming the active application
- exiting itself before the GUI finished loading

This was ugly, hacky, slow and generally not good - but the best solution I had at the time.

Coming up with the separate dart app seemed like a much better idea to me, but now that they are separate I don't really see a way to have it be a sort of "private feature" the main app accesses for you (until they implement launching Flutter apps without GUI active.) If you have thoughts on how to do so with this limitation, or other alternatives, I'd love the input 😁 🌈

**Comment by BlueManCZ** [comment]
I see. Well, what about do it the other way? I don't understand flutter nor dart, so maybe it doesn't make sense, but what about extending "self-contained dart application" a little bit, so it would accept launch flags, and it would launch the flutter GUI only if the user asked for it? If you know what I mean. Something like `dart-app --toogle` and `dart-app --gui`, while the second command could be the same as just `dart-app` without flags.

**Comment by Merrit** [comment]
It could be possible to do something like having a user-facing executable whose job it is to launch the appropriate secondary executable.. like no flags = GUI, but `--toggle` flag launches the toggle executable.

I'm not sure I see the advantage of doing so however; adding file size, complexity & delayed runtime. Things as they are work well, and it can eventually be integrated when Flutter adds the option to trigger the GUI manually, no?

I am definitely going to add a response to CLI flags though..

**Comment by BlueManCZ** [comment]
Yes, you are probably right. If there will be no complaints from other people, leave it be and wait for Flutter CLI handling. Now it's only my view of things versus yours.

> I'm not sure I see the advantage of doing so however

The advantage I see is user-friendly behaviour and the ability to easily install Nyrna to the Linux system, I mentioned in the first post. (Only one executable would be added somewhere to the $PATH)

Currently, it is not very clear for new folks how those two executables work and how they associate together and you should at least explain it in the readme.

**Comment by Merrit** [comment]
> Only one executable would be added somewhere to the $PATH

If adding to path, would you not want both items included so you could do `nyrna` and `toggle_active_window` without having to specify the whole path? I think I'd probably have expected them both to be available.. :woman_shrugging: 

> Currently, it is not very clear for new folks how those two executables work and how they associate together and you should at least explain it in the readme.

Are you including the [usage instructions from the website](https://nyrna.merritt.codes/usage) being not clear, or just the README on the repo?

**Comment by BlueManCZ** [comment]
Yes, but I meant `toggle_active_window` is not a very clear name for the executable and it should be at least renamed to contain nyrna in its name. When I for example look in the `history` after one year, I will possibly not remember what that command was for and I will certainly not find my scripts with `history | grep nyrna`.

Instructions from the website are great. I meant there are no instructions in the released portable.zip nor the source code archives.

**Comment by Merrit** [comment]
>Yes, but I meant toggle_active_window is not a very clear name for the executable and it should be at least renamed to contain nyrna in its name. When I for example look in the history after one year, I will possibly not remember what that command was for and I will certainly not find my scripts with history | grep nyrna.

Excellent point!

> there are no instructions in the released portable.zip

Great point again! Never considered having something included with it.

> nor the source code archives

They are actually included `<source>/docs/_pages/usage.md` -- this is the source file that compiles to the web page -- but that definitely wouldn't be super discoverable when browsing the source..


I already fixed the primary executable to return a meaningful message when given an unknown flag, so at the least I will also look into including instructions and renaming the toggle executable. Do you think copying the `usage.md` into the portable folder would be sufficient, or would something else be better perhaps?

**Comment by BlueManCZ** [comment]
> They are actually included <source>/docs/_pages/usage.md -- this is the source file that compiles to the web page -- but that definitely wouldn't be super discoverable when browsing the source..

Nice. I definitely didn't notice. :grin:

In my opinion, adding the Usage section to the [README.md](https://github.com/Merrit/nyrna/blob/master/README.md) and providing it in the portable folder is the best solution.
