### ISSUE TITLE
Pause doesn't work if changed to another language

### ISSUE THREAD

**Issue by Casul51** [Merrit/nyrna#5]
Well, On eng keyboard layout everything good and works, but when I switch to russian (probably any other) pausing (and resuming) don't works

**Comment by Merrit** [comment]
This issue is a bit tricky.

There is a new release of Nyrna, 1.1. This version allows you to rebind the hotkey to whatever you choose, as well as some code changes to how it sets & recognizes the hotkey.

If it still fails to recognize the key after switching languages, perhaps you can try a different key that might work through switches.

**Comment by Casul51** [comment]
Well, after changing key to same key in another layout it start to act really strange. When RU layout it works as it should if on ENG - it thinks that it pressed 2 times (suspends and resumes or vice versa)

**Comment by Merrit** [comment]
This is actually because at the moment when you change the hotkey, the previous hotkey is still active until Nyrna is restarted. So try closing and starting Nyrna after rebinding the hotkey.

**Comment by Merrit** [comment]
The new version of Nyrna should resolve the issue with the old hotkey remaining active. Has this resolved the issue for you?
